### ISSUE TITLE
How to test - Removing user from AG is supposed to remove them from the OG

### ISSUE THREAD

**Issue by nrackleff** [thinkshout/mandrill_groups#13]
I set Ned Flanders affiliation status to inactive by unchecking the ‘active status’ box on the connection to the AG, but he is still an active member of the associated OG when he should have been removed from OG.

**Comment by nrackleff** [comment]
After further conversation with Lev, I was wrong about the intended behavior. It should only remove a user from the OG if they are actually 'deleted' from the AG, not just set to inactive. Not a bug afterall.

**Comment by nrackleff** [comment]
It was not readily apparent how to 'delete' a connection, so I was not able to test this functionality. Please advise?

**Comment by levelos** [comment]
You can do it via Drush. `drush eval "relation_delete(...)"`

**Comment by nrackleff** [comment]
Works as expected. User is removed from mandrill group when deleted from AG.
