### ISSUE TITLE
upload form for new discussions

### ISSUE THREAD

**Issue by levelos** [thinkshout/mandrill_groups#4]
Currently disappears when hitting the upload button. Take a look at `mandrill_groups_form_mandrill_groups_discussion_node_form_alter()`.

**Comment by levelos** [comment]
Nice!

**Comment by nrackleff** [comment]
As @lev discovered, the fix did not work. It stopped the initial error where the field was disappearing, but the file is not getting associated with the comment.  I will dive back into this again on Monday. 

Notice: Undefined index: field in field_widget_field() (line 578 of /Users/nancyrackleff/Sites/0b5919c0.ngrok.io/modules/field/field.form.inc).

The line where it’s failing: 
function field_widget_field($element, $form_state) {
  $field_state = field_form_get_state($element['#field_parents'], $element['#field_name'], $element['#language'], $form_state);
  return $field_state['field'];
}

**Comment by nrackleff** [comment]
I'm finding lots of similar instances of this:
https://www.drupal.org/node/1336212
https://www.drupal.org/node/1541980
But sadly, no answer that seems to solve it yet.

**Comment by nrackleff** [comment]
@levelos I worked on this with Greg for a while this morning and did not solve the problem. We tried both #14 and #18 on https://www.drupal.org/node/1336212#comment-6049694. Neither one solved the issue. There must to be something different between the comment form when it is embedded in a new node form and when it is by itself.  Similar issue happening when field field is embedded in a field collection. https://www.drupal.org/node/1187010#comment-10030993

**Comment by nrackleff** [comment]
@levelos Is it out of the question to have someone create the topic and save it before they add a comment? Not a great user experience, huh?

**Comment by nrackleff** [comment]
Just reverted the original commit that I made, since it did not fix the problem after all.

**Comment by nrackleff** [comment]
As per discussion with @levelos, we are going to have the user create the topic and save it before they add a comment. Will add some messaging to tell them they will create title first and then add the comment.
