### ISSUE TITLE
Group/discussion privacy 

### ISSUE THREAD

**Issue by levelos** [thinkshout/mandrill_groups#5]

**Comment by nrackleff** [comment]
1. No longer getting WSOD, but now when I am logged in as member and mark a discussion as private, I can still see that discussion in the list of discussions. I assume it should not show up in the list if I am not logged in and/or not a member of the group. @levelos is that correct?  
2. Public discussions are not showing any content to anonymous in users. For example, I have a public discussion with several comments on it. When I view that discussion while logged in as a group member, I do see all of the comments. When I view  the same page not logged in, I see the title and it lists the group visibility as "Public - accessible to all site users", but I do not see any of the comments.

**Comment by nrackleff** [comment]
@levelos I was able to solve item 2 in this issue by adding permission for anonymous and authenticated users to the gf_permissions feature. The code is checked into the mandrill_groups branch of the givingforum repo. https://github.com/thinkshout/givingforum/commit/104c32af9a216d4a5deba957906de751ecbb1b4d

**Comment by nrackleff** [comment]
This appears to be fixed as of https://github.com/thinkshout/mandrill_groups/commit/65a02d0738716b9a546434edcb07cea8d40fc895
